"""Abstract LLM provider interface and neutral message data structures."""

from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from agentkit.core.types import Role
from agentkit.tools.models import ToolCall, ToolSchema


class TokenUsage(BaseModel):
    """Token consumption metrics for a model interaction."""

    model_config = ConfigDict(frozen=True)

    input_tokens: int = Field(default=0, ge=0, description="Tokens in prompt/context.")
    output_tokens: int = Field(default=0, ge=0, description="Tokens generated by model.")

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed across input and output."""
        return self.input_tokens + self.output_tokens


class Message(BaseModel):
    """Neutral representation of a conversational turn across any model provider."""

    model_config = ConfigDict(frozen=True)

    role: Role = Field(description="Participant role: system, user, assistant, or tool.")
    content: str = Field(default="", description="Textual body of the message.")
    tool_calls: list[ToolCall] = Field(
        default_factory=list,
        description="Tool calls requested by the model in an assistant message.",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="ID of the matching tool call if role is 'tool'.",
    )

    @classmethod
    def system(cls, content: str) -> "Message":
        """Construct a system-level directive message."""
        return cls(role=Role.SYSTEM, content=content)

    @classmethod
    def user(cls, content: str) -> "Message":
        """Construct a user prompt message."""
        return cls(role=Role.USER, content=content)

    @classmethod
    def assistant(
        cls,
        content: str = "",
        tool_calls: list[ToolCall] | None = None,
    ) -> "Message":
        """Construct an assistant response message with optional tool requests."""
        return cls(
            role=Role.ASSISTANT,
            content=content,
            tool_calls=tool_calls or [],
        )

    @classmethod
    def tool_result(cls, tool_call_id: str, content: str) -> "Message":
        """Construct a tool result message answering a specific tool call ID."""
        return cls(
            role=Role.TOOL,
            content=content,
            tool_call_id=tool_call_id,
        )


class LLMResponse(BaseModel):
    """Neutral response object returned by an LLMClient."""

    model_config = ConfigDict(frozen=True)

    text: str = Field(default="", description="Natural language output text.")
    tool_calls: list[ToolCall] = Field(
        default_factory=list,
        description="Tool invocations requested by the model.",
    )
    usage: TokenUsage = Field(
        default_factory=TokenUsage,
        description="Token consumption metadata.",
    )
    raw_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw provider-specific metadata and response headers.",
    )


class LLMClient(ABC):
    """Abstract interface defining required behavior for all LLM provider adapters."""

    @abstractmethod
    async def chat(
        self,
        messages: list[Message],
        tools: list[ToolSchema] | None = None,
    ) -> LLMResponse:
        """Send messages and available tool schemas to LLM provider.

        Args:
            messages: Ordered sequence of conversational turns.
            tools: Optional tool schemas exposed to the model for function calling.

        Returns:
            Neutral LLMResponse with text and/or requested tool calls.
        """
        pass
